#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Copy virtual.yaml
if [[ -f "${PWD}/config/virtual.yaml" ]]; then
    rm "${PWD}/config/virtual.yaml"
fi

cp "${PWD}/custom_components/ai_assistant/virtual.yaml" "${PWD}/config/"

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/ai_assistant
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
hass --config "${PWD}/config" --debug
